DROP DATABASE IF EXISTS MyCloudDB;
CREATE DATABASE MyCloudDB;

DROP TABLE IF EXISTS MyCloudDB.Users;
CREATE TABLE MyCloudDB.Users 
(
	UserId INTEGER AUTO_INCREMENT PRIMARY KEY,
	UserName NVARCHAR(128),
	UserPassword NVARCHAR(256)
);

DROP TABLE IF EXISTS MyCloudDB.FileHashes;
CREATE TABLE MyCloudDB.FileHashes
(
	HashId INTEGER AUTO_INCREMENT PRIMARY KEY,
	FullPath NVARCHAR(512) NOT NULL,
	RelativePath NVARCHAR(255) NOT NULL,
	HashCode NVARCHAR(64) NOT NULL,
	--TimeStamp DATETIME NOT NULL
);




/*
DROP TABLE IF EXISTS FileHashes;
CREATE TABLE FileHashes
(
	HashId BIGINT AUTO_INCREMENT PRIMARY KEY,
	ChangeType NVARCHAR(10) NOT NULL,
	FullPath NVARCHAR(255) NOT NULL,
	Name NVARCHAR(32) NOT NULL,
	WasReadOnly BOOLEAN NOT NULL,
	Size BIGINT,
	Created DATETIME,
	Modified DATETIME,
	Accessed DATETIME,
	OldName NVARCHAR(32)
); 
*/